//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineClicker.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineClicker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go back.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talk in chat.
        /// </summary>
        public static string ChatButton {
            get {
                return ResourceManager.GetString("ChatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins: $.
        /// </summary>
        public static string Coins {
            get {
                return ResourceManager.GetString("Coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        public static string ConfigButton {
            get {
                return ResourceManager.GetString("ConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clics/sec:.
        /// </summary>
        public static string CountClicks {
            get {
                return ResourceManager.GetString("CountClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DescriptionP1 {
            get {
                return ResourceManager.GetString("DescriptionP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DescriptionP10 {
            get {
                return ResourceManager.GetString("DescriptionP10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DescriptionP2 {
            get {
                return ResourceManager.GetString("DescriptionP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DescriptionP3 {
            get {
                return ResourceManager.GetString("DescriptionP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DescriptionP4 {
            get {
                return ResourceManager.GetString("DescriptionP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DescriptionP5 {
            get {
                return ResourceManager.GetString("DescriptionP5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DescriptionP6 {
            get {
                return ResourceManager.GetString("DescriptionP6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DescriptionP7 {
            get {
                return ResourceManager.GetString("DescriptionP7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DescriptionP8 {
            get {
                return ResourceManager.GetString("DescriptionP8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DescriptionP9 {
            get {
                return ResourceManager.GetString("DescriptionP9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destroyed blocks: .
        /// </summary>
        public static string DestroyedBlocks {
            get {
                return ResourceManager.GetString("DestroyedBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter e-Mail :.
        /// </summary>
        public static string eMail {
            get {
                return ResourceManager.GetString("eMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string EmailLogin {
            get {
                return ResourceManager.GetString("EmailLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string EnglishButton {
            get {
                return ResourceManager.GetString("EnglishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter friend name : .
        /// </summary>
        public static string FriendName {
            get {
                return ResourceManager.GetString("FriendName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string FriendRequestButton {
            get {
                return ResourceManager.GetString("FriendRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request sent.
        /// </summary>
        public static string FriendRequestSentMessage {
            get {
                return ResourceManager.GetString("FriendRequestSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend username: .
        /// </summary>
        public static string FriendUsernameTag {
            get {
                return ResourceManager.GetString("FriendUsernameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        public static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send invitation .
        /// </summary>
        public static string InvitationButton {
            get {
                return ResourceManager.GetString("InvitationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Japanese.
        /// </summary>
        public static string JapaneseButton {
            get {
                return ResourceManager.GetString("JapaneseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string LanguageTag {
            get {
                return ResourceManager.GetString("LanguageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start multiplayer.
        /// </summary>
        public static string MultiplayerButton {
            get {
                return ResourceManager.GetString("MultiplayerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amber.
        /// </summary>
        public static string NameP1 {
            get {
                return ResourceManager.GetString("NameP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amethyst.
        /// </summary>
        public static string NameP10 {
            get {
                return ResourceManager.GetString("NameP10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copper.
        /// </summary>
        public static string NameP2 {
            get {
                return ResourceManager.GetString("NameP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coal.
        /// </summary>
        public static string NameP3 {
            get {
                return ResourceManager.GetString("NameP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diamond.
        /// </summary>
        public static string NameP4 {
            get {
                return ResourceManager.GetString("NameP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fluorite.
        /// </summary>
        public static string NameP5 {
            get {
                return ResourceManager.GetString("NameP5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iron.
        /// </summary>
        public static string NameP6 {
            get {
                return ResourceManager.GetString("NameP6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bone.
        /// </summary>
        public static string NameP7 {
            get {
                return ResourceManager.GetString("NameP7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wood.
        /// </summary>
        public static string NameP8 {
            get {
                return ResourceManager.GetString("NameP8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Platinum.
        /// </summary>
        public static string NameP9 {
            get {
                return ResourceManager.GetString("NameP9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create an account.
        /// </summary>
        public static string NewAccountButton {
            get {
                return ResourceManager.GetString("NewAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doesn´t have an account yet?.
        /// </summary>
        public static string NewAccountMessage {
            get {
                return ResourceManager.GetString("NewAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your friend is offline.
        /// </summary>
        public static string OfflineFriendMessage {
            get {
                return ResourceManager.GetString("OfflineFriendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string PasswordLogin {
            get {
                return ResourceManager.GetString("PasswordLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins: $ 30.0.
        /// </summary>
        public static string PriceP1 {
            get {
                return ResourceManager.GetString("PriceP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins: $ 120.
        /// </summary>
        public static string PriceP10 {
            get {
                return ResourceManager.GetString("PriceP10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins: $ 40.0.
        /// </summary>
        public static string PriceP2 {
            get {
                return ResourceManager.GetString("PriceP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins: $ 50.0.
        /// </summary>
        public static string PriceP3 {
            get {
                return ResourceManager.GetString("PriceP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins: $ 60.0.
        /// </summary>
        public static string PriceP4 {
            get {
                return ResourceManager.GetString("PriceP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins: $ 70.0.
        /// </summary>
        public static string PriceP5 {
            get {
                return ResourceManager.GetString("PriceP5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins: $ 80.0.
        /// </summary>
        public static string PriceP6 {
            get {
                return ResourceManager.GetString("PriceP6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins: $ 90.
        /// </summary>
        public static string Pricep7 {
            get {
                return ResourceManager.GetString("Pricep7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins: $ 100.
        /// </summary>
        public static string PriceP8 {
            get {
                return ResourceManager.GetString("PriceP8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins: $ 110.
        /// </summary>
        public static string PriceP9 {
            get {
                return ResourceManager.GetString("PriceP9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username or email are already registered.
        /// </summary>
        public static string RegisterFailMessage {
            get {
                return ResourceManager.GetString("RegisterFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player registered successfully.
        /// </summary>
        public static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Second Name.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string SendFriendRequestButton {
            get {
                return ResourceManager.GetString("SendFriendRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        public static string SendInvitationButton {
            get {
                return ResourceManager.GetString("SendInvitationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ask a friend to join the game!.
        /// </summary>
        public static string SendInvitationTag {
            get {
                return ResourceManager.GetString("SendInvitationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player username not found.
        /// </summary>
        public static string SendRequestFailedMessage {
            get {
                return ResourceManager.GetString("SendRequestFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send friend request.
        /// </summary>
        public static string SendRequestTag {
            get {
                return ResourceManager.GetString("SendRequestTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string SpanishButton {
            get {
                return ResourceManager.GetString("SpanishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stats.
        /// </summary>
        public static string StatsButton {
            get {
                return ResourceManager.GetString("StatsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peak Store.
        /// </summary>
        public static string StoreButton {
            get {
                return ResourceManager.GetString("StoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send friend request.
        /// </summary>
        public static string TitleAddFriend {
            get {
                return ResourceManager.GetString("TitleAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite a friend.
        /// </summary>
        public static string TitleInvitation {
            get {
                return ResourceManager.GetString("TitleInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mine Clicker.
        /// </summary>
        public static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplayer.
        /// </summary>
        public static string TitleMultiplayer {
            get {
                return ResourceManager.GetString("TitleMultiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Register.
        /// </summary>
        public static string TitleRegister {
            get {
                return ResourceManager.GetString("TitleRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Store.
        /// </summary>
        public static string TitleStore {
            get {
                return ResourceManager.GetString("TitleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting Game.
        /// </summary>
        public static string TitleWaitingWindow {
            get {
                return ResourceManager.GetString("TitleWaitingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Winner.
        /// </summary>
        public static string TitleWinnerWindow {
            get {
                return ResourceManager.GetString("TitleWinnerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for a partner to join the game....
        /// </summary>
        public static string WaitingMessage {
            get {
                return ResourceManager.GetString("WaitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The winner is: .
        /// </summary>
        public static string WinnerMessage {
            get {
                return ResourceManager.GetString("WinnerMessage", resourceCulture);
            }
        }
    }
}
